# Generated by Django 4.1.6 on 2023-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mySocialApp", "0002_dweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
